function rk_style(ax)
%RK_STYLE Apply the manuscript figure style to one axes.
%   Single place that defines every shared visual property, so all figures in
%   the paper match: font, font sizes, line widths, tick direction, box, grid.
%   No titles are ever set here; the caption carries the description.
if nargin < 1, ax = gca; end
set(ax, ...
    'FontName',        rk_font(), ...
    'FontSize',        9, ...
    'LineWidth',       0.75, ...
    'TickDir',         'out', ...
    'TickLength',      [0.015 0.015], ...
    'Box',             'off', ...
    'XColor',          [0.15 0.15 0.15], ...
    'YColor',          [0.15 0.15 0.15], ...
    'GridColor',       [0.80 0.80 0.80], ...
    'GridAlpha',       1.0, ...
    'GridLineStyle',   ':', ...
    'Layer',           'top');
ax.XAxis.FontName = rk_font();
ax.YAxis.FontName = rk_font();
ax.Title.String = '';                       % enforce: no figure titles
lg = findobj(ax.Parent, 'Type', 'Legend');
for k = 1:numel(lg)
    set(lg(k), 'FontName', rk_font(), 'FontSize', 8, ...
               'Box', 'off', 'AutoUpdate', 'off');
end
end
